package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> bubbleSort(T[] arr) {
        List<SortEvent<Integer>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length - i - 1; j++) {
                events.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    events.add(new SwapEvent<>(j, j + 1));
                    swap(arr, j, j + 1);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> selectionSort(
            T[] arr) {
        int lowestIdx = 0;
        List<SortEvent<Integer>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            lowestIdx = i;
            for (int j = i; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, lowestIdx));
                if (arr[j].compareTo(arr[lowestIdx]) < 0) {
                    lowestIdx = j;
                }
            }
            if (lowestIdx != i) {
                events.add(new SwapEvent<>(i, lowestIdx));
                swap(arr, i, lowestIdx);
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> insertionSort(
            T[] arr) {
        List<SortEvent<Integer>> events = new ArrayList<>();
        for (int i = 1; i < arr.length; i++) {
            for (int j = i; j > 0; j--) {
                events.add(new CompareEvent<>(j, j - 1));
                if (arr[j].compareTo(arr[j - 1]) < 0) {
                    events.add(new SwapEvent<>(j, j - 1));
                    swap(arr, j, j - 1);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param l   the left index
     * @param m   the middle index
     * @param r   the right index
     */
    public static <T extends Comparable<? super T>> 
    List<SortEvent<Integer>> merge(
            T[] arr,
             int l,
              int m,
               int r
               ) {
        List<SortEvent<Integer>> events = new ArrayList<>();
        int n1 = m - l + 1;
        int n2 = r - m;

        // Create Lists instead of arrays to avoid unsafe casting
        List<T> L = new ArrayList<>(n1);
        List<T> R = new ArrayList<>(n2);

        // Copy data to temp lists
        for (int i = 0; i < n1; ++i) {
            events.add(new CopyEvent<>(i, l + i));
            L.add(arr[l + i]);
        }
        for (int j = 0; j < n2; ++j) {
            events.add(new CopyEvent<>(j, m + 1 + j));
            R.add(arr[m + 1 + j]);
        }

        int i = 0, j = 0;
        int k = l;
        while (i < n1 && j < n2) {
            events.add(new CompareEvent<>(l + i, m + 1 + j));
            if (L.get(i).compareTo(R.get(j)) <= 0) {
                arr[k] = L.get(i);
                i++;
            } else {
                arr[k] = R.get(j);
                j++;
            }
            k++;
        }

        while (i < n1) {
            events.add(new CopyEvent<>(k, i));
            arr[k] = L.get(i);
            i++;
            k++;
        }

        while (j < n2) {
            events.add(new CopyEvent<>(k, j));
            arr[k] = R.get(j);
            j++;
            k++;
        }

        return events;
    }

    /**
     * Merge sort method that sorts the array and returns a list of SortEvents.
     * 
     * @param <T> the type of elements in the array
     * @param arr the array to sort
     * @return the list of sort events
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> mergeSort(T[] arr) {
        return sort(arr, 0, arr.length - 1);
    }

    /**
     * Recursive method that sorts arr[l..r] using merge sort.
     * 
     * @param <T> the type of elements in the array
     * @param arr the array to sort
     * @param l   the left index
     * @param r   the right index
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> sort(
            T[] arr,
            int l,
            int r) {
        if (l < r) {
            int m = l + (r - l) / 2;
            sort(arr, l, m);
            sort(arr, m + 1, r);
            return merge(arr, l, m, r);
        }
        return null;
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        quickSortHelper(arr, 0, arr.length - 1, events);
        return events;
    }

    private static <T extends Comparable<? super T>> void quickSortHelper(
            T[] arr, int l, int r, List<SortEvent<T>> events) {
        if (l >= r) {
            return;
        }

        T pivot = arr[l + (r - l) / 2];
        int i = l, j = r;

        while (i <= j) {
            while (arr[i].compareTo(pivot) < 0) {
                events.add(new CompareEvent<>(i, l + (r - l) / 2));
                i++;
            }
            while (arr[j].compareTo(pivot) > 0) {
                events.add(new CompareEvent<>(j, l + (r - l) / 2));
                j--;
            }
            if (i <= j) {
                events.add(new CompareEvent<>(i, j));
                swap(arr, i, j);
                events.add(new SwapEvent<>(i, j));
                i++;
                j--;
            }
        }

        // Recursive calls for the two partitions
        if (l < j) {
            quickSortHelper(arr, l, j, events);
        }
        if (i < r) {
            quickSortHelper(arr, i, r, events);
        }
    }

    /**
     * Performs Heap Sort on the given array.
     * 
     * @param arr the array to sort
     * @param <T> the type of elements in the array (extends Comparable)
     * @return a list of SortEvents representing the sorting process
     */
    public static <T extends Comparable<T>> List<SortEvent<T>> heapSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int n = arr.length;

        // Build a max heap
        for (int i = n / 2 - 1; i >= 0; i--) {
            heapify(arr, n, i, events);
        }

        // One by one extract elements from the heap
        for (int i = n - 1; i >= 1; i--) {
            // Move current root to the end
            events.add(new SwapEvent<>(0, i));
            swap(arr, 0, i);

            // Call heapify on the reduced heap
            heapify(arr, i, 0, events);
        }

        return events;
    }

    /**
     * To heapify a subtree rooted with node i, which is an index in arr[].
     * n is the size of the heap.
     * 
     * @param arr    the array representing the heap
     * @param n      the size of the heap
     * @param i      the index of the root of the subtree to heapify
     * @param events list of SortEvents
     * @param <T>    the type of elements in the array (extends Comparable)
     */
    private static <T extends Comparable<T>> void heapify(
            T[] arr,
            int n,
            int i,
            List<SortEvent<T>> events) {
        int largest = i; // Initialize largest as root
        int left = 2 * i + 1; // left = 2*i + 1
        int right = 2 * i + 2; // right = 2*i + 2

        // If left child is larger than root
        if (left < n && arr[left].compareTo(arr[largest]) > 0) {
            largest = left;
        }

        // If right child is larger than largest so far
        if (right < n && arr[right].compareTo(arr[largest]) > 0) {
            largest = right;
        }

        // If largest is not root
        if (largest != i) {
            events.add(new SwapEvent<>(i, largest));
            swap(arr, i, largest);

            // Recursively heapify the affected subtree
            heapify(arr, n, largest, events);
        }
    }
}
