package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> bubbleSort(T[] arr) {
        List<SortEvent<Integer>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length - i - 1; j++) {
                events.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    events.add(new SwapEvent<>(j, j + 1));
                    swap(arr, j, j + 1);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> selectionSort(
            T[] arr) {
        int lowestIdx = 0;
        List<SortEvent<Integer>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            lowestIdx = i;
            for (int j = i; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, lowestIdx));
                if (arr[j].compareTo(arr[lowestIdx]) < 0) {
                    lowestIdx = j;
                }
            }
            if (lowestIdx != i) {
                events.add(new SwapEvent<>(i, lowestIdx));
                swap(arr, i, lowestIdx);
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> insertionSort(
            T[] arr) {
        List<SortEvent<Integer>> events = new ArrayList<>();
        for (int i = 1; i < arr.length; i++) {
            for (int j = i; j > 0; j--) {
                events.add(new CompareEvent<>(j, j - 1));
                if (arr[j].compareTo(arr[j - 1]) < 0) {
                    events.add(new SwapEvent<>(j, j - 1));
                    swap(arr, j, j - 1);
                }
            }
        }
        return events;
    }

   /**
 * Performs merge sort on the given array.
 * 
 * @param <T> the carrier type of the array
 * @param arr the array to sort
 * @return the sort events generated by this sort
 */
public static <T extends Comparable<? super T>> List<SortEvent<Integer>> mergeSort(T[] arr) {
    List<SortEvent<Integer>> events = new ArrayList<>();
    @SuppressWarnings("unchecked")
    T[] tempArray = (T[]) new Comparable[arr.length];
    mergeSortHelper(arr, 0, arr.length - 1, tempArray, events);
    return events;
}

/**
 * Helper method that recursively sorts parts of the array.
 * 
 * @param <T> the carrier type of the array
 * @param arr the array to sort
 * @param left the start index
 * @param right the end index
 * @param tempArray temporary array for merging
 * @param events list to collect sorting events
 */
private static <T extends Comparable<? super T>> void mergeSortHelper(
        T[] arr, int left, int right, T[] tempArray, List<SortEvent<Integer>> events) {
    if (left < right) {
        int mid = left + (right - left) / 2;
        mergeSortHelper(arr, left, mid, tempArray, events);
        mergeSortHelper(arr, mid + 1, right, tempArray, events);
        mergeHalves(arr, left, mid, right, tempArray, events);
    }
}

/**
 * Merges two sorted subarrays into one.
 * 
 * @param <T> the carrier type of the array
 * @param arr the array containing both subarrays
 * @param left the start index of the first subarray
 * @param mid the end index of the first subarray
 * @param right the end index of the second subarray
 * @param tempArray temporary array for merging
 * @param events list to collect sorting events
 */
private static <T extends Comparable<? super T>> void mergeHalves(
        T[] arr, int left, int mid, int right, T[] tempArray, List<SortEvent<Integer>> events) {
    for (int i = left; i <= right; i++) {
        tempArray[i] = arr[i];
    }
    
    int i = left;
    int j = mid + 1;
    int k = left;  
    
    while (i <= mid && j <= right) {
        events.add(new CompareEvent<>(i, j)); 
        if (tempArray[i].compareTo(tempArray[j]) <= 0) {
            arr[k] = tempArray[i];
            events.add(new CopyEvent<>(k, i));
            i++;
        } else {
            arr[k] = tempArray[j];
            events.add(new CopyEvent<>(k, j));
            j++;
        }
        k++;
    }
    while (i <= mid) {
        arr[k] = tempArray[i];
        events.add(new CopyEvent<>(k, i));
        i++;
        k++;
    }
    
    while (j <= right) {
        arr[k] = tempArray[j];
        events.add(new CopyEvent<>(k, j));
        j++;
        k++;
    }
}

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        quickSortHelper(arr, 0, arr.length - 1, events);
        return events;
    }

    private static <T extends Comparable<? super T>> void quickSortHelper(
            T[] arr, int l, int r, List<SortEvent<T>> events) {
        if (l >= r) {
            return;
        }

        T pivot = arr[l + (r - l) / 2];
        int i = l, j = r;

        while (i <= j) {
            while (arr[i].compareTo(pivot) < 0) {
                events.add(new CompareEvent<>(i, l + (r - l) / 2));
                i++;
            }
            while (arr[j].compareTo(pivot) > 0) {
                events.add(new CompareEvent<>(j, l + (r - l) / 2));
                j--;
            }
            if (i <= j) {
                events.add(new CompareEvent<>(i, j));
                swap(arr, i, j);
                events.add(new SwapEvent<>(i, j));
                i++;
                j--;
            }
        }

        if (l < j) {
            quickSortHelper(arr, l, j, events);
        }
        if (i < r) {
            quickSortHelper(arr, i, r, events);
        }
    }

    /**
     * Performs Heap Sort on the given array.
     * 
     * @param arr the array to sort
     * @param <T> the type of elements in the array (extends Comparable)
     * @return a list of SortEvents representing the sorting process
     */
    public static <T extends Comparable<T>> List<SortEvent<T>> heapSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int n = arr.length;
        for (int i = n / 2 - 1; i >= 0; i--) {
            heapify(arr, n, i, events);
        }
        for (int i = n - 1; i >= 1; i--) {
            events.add(new SwapEvent<>(0, i));
            swap(arr, 0, i);
            heapify(arr, i, 0, events);
        }
        return events;
    }

    /**
     * To heapify a subtree rooted with node i, which is an index in arr[].
     * n is the size of the heap.
     * 
     * @param arr    the array representing the heap
     * @param n      the size of the heap
     * @param i      the index of the root of the subtree to heapify
     * @param events list of SortEvents
     * @param <T>    the type of elements in the array (extends Comparable)
     */
    private static <T extends Comparable<T>> void heapify(
            T[] arr,
            int n,
            int i,
            List<SortEvent<T>> events) {
        int largest = i; 
        int left = 2 * i + 1; 
        int right = 2 * i + 2;
        if (left < n && arr[left].compareTo(arr[largest]) > 0) {
            largest = left;
        }
        if (right < n && arr[right].compareTo(arr[largest]) > 0) {
            largest = right;
        }
        if (largest != i) {
            events.add(new SwapEvent<>(i, largest));
            swap(arr, i, largest);
            heapify(arr, n, largest, events);
        }
    }
}
